name: aqt
favicon: null
layout_spectrum: 0.8882841959130019
typography_spectrum: 0.7568106709513813
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4460987984202802
  lightness: 0.2235001940280199
  saturation: 0.7462953890208155
  rhythmicContrast: 0.7083018678240478
purpose: []
